#!/usr/bin/env python3
"""Publish FluCoMa audio descriptors from the LIRA-8 patch as OSC buses.

TouchDesigner cannot see inside Pd, so the two talk over OSC, and
tools/osc_bridge_source.py publishes every bus it scans out of _LIRA-8.pd.
This script only has to get the analysis values onto $0-s-<name> sends there.

Two artifacts come out of one table:

  abs/av.audio.pd   one signal inlet and one control outlet per row
  _LIRA-8.pd        an appended block feeding the master audio in and
                    wiring each outlet to [s $0-s-<name>]

Each row maps its input window linearly onto 0..127 and clips, because every
binding expression in tools/td_build.py divides by 127.0. Adding a descriptor
is one row here, with no change to the bridge and no per-descriptor branch.
"""

import sys
from collections import namedtuple
from pathlib import Path

from pd_text import connect, item

ROOT = Path(__file__).resolve().parent.parent
PATCH = ROOT / "_LIRA-8.pd"
ABSTRACTION = ROOT / "abs" / "av.audio.pd"

# $0 keeps the buses private to one patch instance, the same convention the
# other controls in _LIRA-8.pd use. The scanner in tools/osc_bridge_source.py
# matches this name.
BUS = "\\$0-s-"
# Anchor for the appended block, so rerunning this script replaces it instead
# of stacking a second copy at the end of the patch.
MARKER = "FluCoMa descriptor stage. Generated by tools/audio_bus_source.py."
OUT_MAX = 127.0

# bus name, source object, index in that object's output list, input low, high
Descriptor = namedtuple("Descriptor", "bus source index low high")

DESCRIPTORS = (
    Descriptor("a-loud", "fluid.loudness~", 0, -60.0, 0.0),
    Descriptor("a-peak", "fluid.loudness~", 1, -60.0, 0.0),
    Descriptor("a-cent", "fluid.spectralshape~", 0, 100.0, 6000.0),
    Descriptor("a-flat", "fluid.spectralshape~", 5, 0.0, 1.0),
    Descriptor("a-pitch", "fluid.pitch~", 0, 30.0, 2000.0),
    Descriptor("a-conf", "fluid.pitch~", 1, 0.0, 1.0),
)

# Creation arguments and output-list length per source object. The length sizes
# the unpack, so a row's index has to stay inside it.
SOURCES = {
    "fluid.loudness~": ("", 2),
    # -unit 0 reports the centroid in Hz. -unit 1 reports a MIDI note, which
    # pins a Hz window at the floor.
    "fluid.spectralshape~": ("-unit 0 -power 1 -minfreq 20", 7),
    "fluid.pitch~": ("", 2),
}


def number(value):
    """Pd reads either form. -60 is easier on the eye than -60.0."""
    return "%d" % value if float(value).is_integer() else repr(float(value))


def emit(objects, links, header=None, base=0):
    """Objects first, then the connects that index into them by key.

    A link end is either a key of one of these objects or an index of an
    object that already lives in the target file. base is how many items the
    target file already has, since Pd counts those first.
    """
    index = {key: i + base for i, (key, kind, x, y, body) in enumerate(objects)}
    lines = [header] if header else []
    lines += [item(kind, x, y, body)
              for key, kind, x, y, body in objects]
    for source, outlet, sink, inlet in links:
        a = index[source] if isinstance(source, str) else source
        b = index[sink] if isinstance(sink, str) else sink
        lines.append(connect(a, outlet, b, inlet))
    return "\n".join(lines) + "\n"


def scale_chain(bus, x, low, high):
    """One column mapping a value in low..high onto 0..127, then clipping.

    A zero-width window has no line to map, so that row multiplies by zero and
    never divides.
    """
    if high == low:
        return ([(bus + ":zero", "obj", x, 80, "* 0")],
                [],
                bus + ":zero", bus + ":zero")
    keys = (bus + ":sub", bus + ":mul", bus + ":clip")
    return ([(keys[0], "obj", x, 40, "- " + number(low)),
             (keys[1], "obj", x, 80, "* " + number(OUT_MAX / (high - low))),
             (keys[2], "obj", x, 120, "clip 0 127")],
            [(keys[0], 0, keys[1], 0), (keys[1], 0, keys[2], 0)],
            keys[0], keys[2])


def abstraction():
    """abs/av.audio.pd. No sends and no bus names, just the analysis.

    Pd orders a canvas's inlets and outlets by horizontal position, and a tie
    on x goes bottom first. Outlets sharing an x would therefore come out in
    reverse row order, so row i gets its own column, left to right, and
    outlet i is table row i.
    """
    objects = [("in", "obj", 30, 60, "inlet~")]
    links = []
    for i, source in enumerate(dict.fromkeys(d.source for d in DESCRIPTORS)):
        args, width = SOURCES[source]
        y = 120 + 50 * i
        objects.append((source, "obj", 30, y, (source + " " + args).strip()))
        objects.append((source + ":unpack", "obj", 150, y,
                        "unpack " + " ".join(["f"] * width)))
        links.append(("in", 0, source, 0))
        links.append((source, 0, source + ":unpack", 0))
    for i, d in enumerate(DESCRIPTORS):
        if d.index >= SOURCES[d.source][1]:
            raise SystemExit("row %s index %d is outside %s's output list (%d)"
                             % (d.bus, d.index, d.source, SOURCES[d.source][1]))
        x = 260 + 90 * i
        chain, chain_links, head, tail = scale_chain(d.bus, x, d.low, d.high)
        objects += chain
        links += chain_links
        objects.append((d.bus + ":out", "obj", x, 160, "outlet"))
        links.append((d.source + ":unpack", d.index, head, 0))
        links.append((tail, 0, d.bus + ":out", 0))
    return emit(objects, links, "#N canvas 0 0 840 300 10;")


def root_items(lines):
    """(items, connects) of the outermost canvas.

    Pd numbers a canvas item by item, text boxes included, but a subpatch
    counts once where its '#X restore' closes it and its contents not at all.
    The connects come back too, because only the root ones index the root.
    """
    items = []
    connects = []
    depth = 0
    opened = False
    for line in lines:
        if line.startswith("#N canvas"):
            if opened:
                depth += 1
            opened = True
            continue
        if not line.startswith("#X"):
            continue
        kind = line.split()[1]
        if kind == "restore":
            depth -= 1
            if depth == 0:
                items.append((len(items), kind, line))
            continue
        if kind == "connect":
            if depth == 0:
                connects.append(line)
            continue
        if kind in ("coords", "declare"):
            continue
        if depth == 0:
            items.append((len(items), kind, line))
    return items, connects


def master_tap(items, connects):
    """Index of the root outlet that drives [dac~ 1 2].

    Fanning out of that same outlet taps the master audio without breaking the
    chain into the dac.
    """
    dac = next(i for i, kind, line in items
               if kind == "obj" and len(line.split()) > 4
               and line.split()[4] == "dac~")
    for line in connects:
        source, _, sink, inlet = (int(v) for v in line.rstrip(";").split()[2:6])
        if sink == dac and inlet == 0:
            return source
    raise SystemExit("no connect feeds [dac~] inlet 0 in the root canvas")


def block(tap, base):
    """The objects and connects appended to _LIRA-8.pd."""
    objects = [("marker", "text", 32, 780, MARKER),
               ("mix", "obj", 32, 800, "catch~ av-mix"),
               ("audio", "obj", 32, 830, "av.audio \\$0"),
               ("mixout", "obj", 560, 800, "throw~ av-mix")]
    # Every DAC feed throws into one named sum, and the analysis catches it, so
    # the analysis hears the whole output instead of one branch of it.
    links = [(tap, 0, "mixout", 0), ("mix", 0, "audio", 0)]
    for i, d in enumerate(DESCRIPTORS):
        key = d.bus + ":send"
        objects.append((key, "obj", 300, 830 + 30 * i, "s " + BUS + d.bus))
        links.append(("audio", i, key, 0))
    return emit(objects, links, base=base)


def stripped(text):
    """Drop a block appended by an earlier run of this script."""
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if MARKER in line:
            return "\n".join(lines[:i]).rstrip("\n") + "\n"
    return text if text.endswith("\n") else text + "\n"


def main():
    if len(sys.argv) > 1:
        sys.exit("usage: audio_bus_source.py")
    patch = stripped(PATCH.read_text())
    lines = patch.splitlines()
    items, connects = root_items(lines)
    tap = master_tap(items, connects)
    PATCH.write_text(patch + block(tap, len(items)))
    ABSTRACTION.write_text(abstraction())
    print("wrote %s (%d descriptors) and appended them to %s off root item %d"
          % (ABSTRACTION.relative_to(ROOT), len(DESCRIPTORS), PATCH.name, tap))


if __name__ == "__main__":
    main()
